name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: cv_ger.tex
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: cv_eng.tex
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cv_current
          path: '*.pdf'
      - name: commit cv files
        uses: EndBug/add-and-commit@v5
        with:
          add: '*.pdf'
          author_name: oxydonth
          author_email: max.bielka@alumni.fh-aachen.de
          branch: gh-pages
          message: 'current cvs'
          push: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged       
