name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cv_current
          path: main.pdf
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'main.pdf'
          destination_repo: 'cv/gh-pages'
          destination_folder: 'pdf'
          user_email: 'max.bielka@alumni.fh-aachen.de'
          user_name: 'oxydonth'
          commit_message: 'Current cv commit'

     
