name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cv_current
          path: main.pdf
      - name: checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          path: "/home/runner/work/cv/cv/cv_pdf_commit_space/"
          ref: gh-pages
      - name: copy to repo
        uses: canastro/copy-action@0.0.2
        with:
          source: main.pdf
          target: /home/runner/work/cv/cv/cv_pdf_commit_space/pdf/main.pdf
      - name: commit to branch
        uses: EndBug/add-and-commit@v5
        with:
          message: "commit current cv Version"
          add: "*.pdf --force"
          cwd: "./pathToRepo/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
